# font = { normal = { family = 'JetbrainsMono Nerd Font' }, size = 11.25 }
font = { normal = { family = 'FiraCode Nerd Font' }, size = 11.5 }
# font = { normal = { family = 'CaskaydiaMono Nerd Font' }, size = 11.5}
